### ISSUE TITLE
Can't compile on neither 4.02.2+multicore nor 4.06.1+multicore

### ISSUE THREAD

**Issue by argent-smith** [ocaml-multicore/reagents#25]
Hello. Tried to install reagents via opam. Didn't Succeed. Here's what I get:

4.06.1:
```
#=== ERROR while compiling reagents.0.3.0 =====================================#
# context     2.0.4 | macos/x86_64 |  | git+https://github.com/ocamllabs/multicore-opam.git
# path        ~/.opam/4.06.1+multicore/.opam-switch/build/reagents.0.3.0
# command     ~/.opam/opam-init/hooks/sandbox.sh build jbuilder build -p reagents -j 11
# exit-code   1
# env-file    ~/.opam/log/reagents-8470-c98387.env
# output-file ~/.opam/log/reagents-8470-c98387.out
### output ###
# [...]
# Please switch to dune instead.
# File "reagents/jbuild", line 1, characters 0-0:
# Warning: jbuild files are deprecated, please convert this file to a dune file instead.
# Note: You can use "dune upgrade" to convert your project to dune.
#       ocamlc reagents/.reagents.objs/byte/reagents__Offer.{cmo,cmt} (exit 2)
# (cd _build/default && /Users/paul/.opam/4.06.1+multicore/bin/ocamlc.opt -w -40 -g -bin-annot -I reagents/.reagents.objs/byte -I /Users/paul/.opam/4.06.1+multicore/lib/kcas -I /Users/paul/.opam/4.06.1+multicore/lib/lockfree -intf-suffix .ml -no-alias-deps -open Reagents__ -o reagents/.reagents.objs/byte/reagents__Offer.cmo -c -impl reagents/offer.ml)
# File "reagents/offer.ml", line 42, characters 17-28:
# Error: Unbound value Kcas.get_id
#     ocamlopt reagents/.reagents.objs/native/reagents__Offer.{cmx,o} (exit 2)
# (cd _build/default && /Users/paul/.opam/4.06.1+multicore/bin/ocamlopt.opt -w -40 -g -I reagents/.reagents.objs/byte -I reagents/.reagents.objs/native -I /Users/paul/.opam/4.06.1+multicore/lib/kcas -I /Users/paul/.opam/4.06.1+multicore/lib/lockfree -intf-suffix .ml -no-alias-deps -open Reagents__ -o reagents/.reagents.objs/native/reagents__Offer.cmx -c -impl reagents/offer.ml)
# File "reagents/offer.ml", line 42, characters 17-28:
# Error: Unbound value Kcas.get_id
```

And here's 4.02.2:

```
#=== ERROR while compiling topkg.1.0.0 ========================================#
# context     2.0.4 | macos/x86_64 | ocaml-variants.4.02.2+multicore | https://opam.ocaml.org#322317ee
# path        ~/.opam/4.02.2+multicore/.opam-switch/build/topkg.1.0.0
# command     ~/.opam/opam-init/hooks/sandbox.sh build ocaml pkg/pkg.ml build --pkg-name topkg --dev-pkg false
# exit-code   1
# env-file    ~/.opam/log/topkg-22768-3c7f0d.env
# output-file ~/.opam/log/topkg-22768-3c7f0d.out
### output ###
# [...]
# ocamlfind ocamldep -package 'bytes result' -modules src/topkg.ml > src/topkg.ml.depends
# pkg.ml: [ERROR] cmd ['ocamlbuild' '-use-ocamlfind' '-classic-display' '-j' '4' '-tag' 'debug'
#      '-build-dir' '_build' 'CHANGES.md' 'LICENSE.md' 'README.md' 'pkg/META'
#      'topkg.opam' 'src/topkg.a' 'src/topkg.cmxs' 'src/topkg.cmxa'
#      'src/topkg.cma' 'src/topkg_vcs.cmx' 'src/topkg_test.cmx'
#      'src/topkg_string.cmx' 'src/topkg_result.cmx' 'src/topkg_publish.cmx'
#      'src/topkg_pkg.cmx' 'src/topkg_os.cmx' 'src/topkg_opam.cmx'
#      'src/topkg_main.cmx' 'src/topkg_log.cmx' 'src/topkg_ipc.cmx'
#      'src/topkg_install.cmx' 'src/topkg_fpath.cmx' 'src/topkg_fexts.cmx'
#      'src/topkg_distrib.cmx' 'src/topkg_conf.cmx' 'src/topkg_codec.cmx'
#      'src/topkg_cmd.cmx' 'src/topkg_build.cmx' 'src/topkg.cmx'
#      'src/topkg.cmi' 'src/topkg.mli']: exited with 255
```

Am I doing something wrong?

**Comment by argent-smith** [comment]
Update: Managed to build it on 4.06.1 by doing `opam pin add kcas --dev-repo`. The libs appear to be out of sync. However I apologize for the panic and thank you for your patience.

**Comment by bartoszmodelski** [comment]
Closing as kcas and reagents build on 5.0.0 (although reagents are not in opam yet). Feel free to reopen if there's any issues.
